version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.2
  gcp-gke: circleci/gcp-gke@0.2.0

jobs:
  build: 
    docker:
     - image: sheenaxyz/node-web-app
    steps:
     # install g cloud
     - gcp-cli install
     - checkout
     - run:
       command: |
        docker build -t sheenaxyz/node-web-app .

