version: 2
jobs:
  build: 
    docker:
     - image: sheenaxyz/node-web-app
    steps:
     - gcp-cli install
     - checkout
     - run:
       command: |
        docker build -t sheenaxyz/node-web-app .

